# Generated by Django 5.1.15 on 2026-02-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When this prayer has been prayed over', null=True)),
                ('text', models.TextField()),
                ('user_ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_allowed_at', models.DateTimeField(help_text='Earliest time this source may submit another prayer')),
                ('user_name', models.CharField(default='Anonymous', help_text='Name of the person submitting the prayer', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_ip_address'], name='iprayio_pra_user_ip_725797_idx'), models.Index(fields=['user_email'], name='iprayio_pra_user_em_819721_idx'), models.Index(fields=['next_allowed_at'], name='iprayio_pra_next_al_4e4906_idx'), models.Index(fields=['fulfilled_at'], name='iprayio_pra_fulfill_645efa_idx')],
            },
        ),
    ]
