# Generated by Django 5.1.15 on 2026-02-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When this prayer has been prayed over', null=True)),
                ('text', models.TextField()),
                ('source_ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('source_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_allowed_at', models.DateTimeField(help_text='Earliest time this source may submit another prayer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_ip_address'], name='iprayio_pra_source__563506_idx'), models.Index(fields=['source_email'], name='iprayio_pra_source__f57169_idx'), models.Index(fields=['next_allowed_at'], name='iprayio_pra_next_al_4e4906_idx'), models.Index(fields=['fulfilled_at'], name='iprayio_pra_fulfill_645efa_idx')],
            },
        ),
    ]
