# Generated by Django 5.1.15 on 2026-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When this prayer has been prayed over', null=True)),
                ('text', models.TextField()),
                ('user_ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('next_allowed_at', models.DateTimeField(help_text='Earliest time this source may submit another prayer')),
                ('user_name', models.CharField(default='Anonymous', help_text='Name of person submitting the prayer', max_length=100)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('sms_error', models.TextField(blank=True, null=True)),
                ('prayer_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('processing', 'Processing'), ('received', 'Received'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='incomplete', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_by', models.CharField(blank=True, max_length=64, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_ip_address'], name='iprayio_pra_user_ip_725797_idx'), models.Index(fields=['content_hash'], name='iprayio_pra_content_2c98b0_idx'), models.Index(fields=['next_allowed_at'], name='iprayio_pra_next_al_4e4906_idx'), models.Index(fields=['fulfilled_at'], name='iprayio_pra_fulfill_645efa_idx')],
            },
        ),
    ]
