# Generated by Django 5.1.15 on 2026-02-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprayio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this prayer has been reviewed and approved for public sharing.'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the user has granted permission for this prayer to be shared publicly'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Optional email address for users who wish to receive updates when their prayer is fulfilled.', max_length=254, null=True),
        ),
    ]
