# Generated by Django 5.1.15 on 2026-02-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprayio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayer',
            name='prayer_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='prayer',
            name='sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='user_name',
            field=models.CharField(default='Anonymous', help_text='Name of person submitting the prayer', max_length=100),
        ),
    ]
