# Generated by Django 5.1.15 on 2026-02-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprayio', '0002_prayer_status_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prayer',
            name='processing_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='prayer_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('processing', 'Processing'), ('received', 'Received'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='incomplete', max_length=20),
        ),
    ]
