# Generated by Django 5.1.15 on 2026-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprayio', '0002_prayer_opt_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
