# Generated by Django 5.1.15 on 2026-02-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iprayio', '0002_prayer_status_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prayer',
            name='processing_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
